# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headphoto',
            field=models.ImageField(default='default/headphoto.jpg', upload_to=''),
        ),
    ]
