# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171031_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageapp',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messageblog',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
