# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='app',
            name='excrept',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='app',
            name='foreImg',
            field=models.ImageField(default='default/foreImg.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(default='default/icon.jpg', upload_to=''),
        ),
    ]
