# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appcomment',
            old_name='game',
            new_name='app',
        ),
    ]
